theme: jekyll-theme-architect
title: Mars City State
description: by SpaceColony.One
image: https://spacecolonyone.github.io/MarsCityState/assets/images/preview.png
show_downloads: false
defaults:
  - values:
      image:
        path: https://spacecolonyone.github.io/MarsCityState/assets/images/preview.png
        height: 600
        width: 900
